### ISSUE TITLE
CentOS 7 下编译安装

### ISSUE THREAD

**Issue by iugo** [iugo/blog#12]
CentOS 7

所以先按照文档安装依赖:

```
yum install epel-release -y
yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel libsodium-devel mbedtls-devel -y
```

然后正式编译 `./autogen.sh && ./configure && make`.

出错, 提示:

```
configure.ac:235: error: required file 'libbloom/Makefile.in' not found
configure.ac:235: error: required file 'libcork/Makefile.in' not found
configure.ac:235: error: required file 'libipset/Makefile.in' not found
autoreconf: automake failed with exit status: 1
```

原因与解决是: https://github.com/shadowsocks/shadowsocks-libev/issues/1095

执行了 `git submodule init && git submodule update`.

再次编译 `./autogen.sh && ./configure && make`.

出错, 提示:

```
configure: error: mbed TLS libraries not found.
```

记得安装过这个依赖呀. 回头再安装一遍依赖 `yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto udns-devel libev-devel libsodium-devel mbedtls-devel -y`, 这时看到了错误:

```
No package udns-devel available.
No package libsodium-devel available.
No package mbedtls-devel available.
```

原来这三个包并未被安装上.

我能想到的好的方法是通过 yum 安装上这些依赖, 可是找不到该修改远程仓库为什么.

然后想直接安装 rpm `https://centos.pkgs.org/7/epel-x86_64/udns-devel-0.4-3.el7.x86_64.rpm.html` 如何? 但是其中的依赖还是无法找到.

这这这, 依赖链还是要通过 `yum` 啊.

...

学艺不精, 最后还是用别人的脚本完成了安装. 别人的脚本就能很好地装依赖. 我...

**Comment by gggin** [comment]
yum install http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/u/udns-0.4-3.el7.x86_64.rpm
yum install http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/u/udns-devel-0.4-3.el7.x86_64.rpm

**Comment by PantherJohn** [comment]
@iugo 2018?
```
yum install epel-release yum-utils -y
yum-config-manager --enable epel
yum install udns-devel -y
```
